apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-09-04T23:03:48Z"
  generation: 1
  labels:
    app: python-billboard-hot-one-hundred-kata
  name: python-billboard-hot-one-hundred-kata
  namespace: default
  resourceVersion: "855"
  uid: bcbf0fab-6a8e-440c-b9a9-c46b275b2e21
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python-billboard-hot-one-hundred-kata
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-billboard-hot-one-hundred-kata
    spec:
      containers:
      - image: caprilespe/python-billboard-hot-one-hundred-kata:v1
        imagePullPolicy: IfNotPresent
        name: python-billboard-hot-one-hundred-kata
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-09-04T23:03:48Z"
    lastUpdateTime: "2022-09-04T23:04:38Z"
    message: ReplicaSet "python-billboard-hot-one-hundred-kata-7fbb757bd4" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-09-04T23:04:39Z"
    lastUpdateTime: "2022-09-04T23:04:39Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
